//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/GroupMessages.proto

package com.gamelift.rt.proto;

@kotlin.jvm.JvmSynthetic
public inline fun groupMembershipUpdate(block: com.gamelift.rt.proto.GroupMembershipUpdateKt.Dsl.() -> kotlin.Unit): com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate =
  com.gamelift.rt.proto.GroupMembershipUpdateKt.Dsl._create(com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate.newBuilder()).apply { block() }._build()
public object GroupMembershipUpdateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate = _builder.build()

    /**
     * <code>int32 group = 1;</code>
     */
    public var group: kotlin.Int
      @JvmName("getGroup")
      get() = _builder.getGroup()
      @JvmName("setGroup")
      set(value) {
        _builder.setGroup(value)
      }
    /**
     * <code>int32 group = 1;</code>
     */
    public fun clearGroup() {
      _builder.clearGroup()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PlayersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated int32 players = 2;</code>
     */
     public val players: com.google.protobuf.kotlin.DslList<kotlin.Int, PlayersProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getPlayersList()
      )
    /**
     * <code>repeated int32 players = 2;</code>
     * @param value The players to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addPlayers")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, PlayersProxy>.add(value: kotlin.Int) {
      _builder.addPlayers(value)
    }/**
     * <code>repeated int32 players = 2;</code>
     * @param value The players to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignPlayers")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, PlayersProxy>.plusAssign(value: kotlin.Int) {
      add(value)
    }/**
     * <code>repeated int32 players = 2;</code>
     * @param values The players to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllPlayers")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, PlayersProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Int>) {
      _builder.addAllPlayers(values)
    }/**
     * <code>repeated int32 players = 2;</code>
     * @param values The players to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllPlayers")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, PlayersProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Int>) {
      addAll(values)
    }/**
     * <code>repeated int32 players = 2;</code>
     * @param index The index to set the value at.
     * @param value The players to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setPlayers")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, PlayersProxy>.set(index: kotlin.Int, value: kotlin.Int) {
      _builder.setPlayers(index, value)
    }/**
     * <code>repeated int32 players = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearPlayers")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, PlayersProxy>.clear() {
      _builder.clearPlayers()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate.copy(block: com.gamelift.rt.proto.GroupMembershipUpdateKt.Dsl.() -> kotlin.Unit): com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate =
  com.gamelift.rt.proto.GroupMembershipUpdateKt.Dsl._create(this.toBuilder()).apply { block() }._build()
