// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/GroupMessages.proto

package com.gamelift.rt.proto;

public final class GroupMessages {
  private GroupMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface JoinGroupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.gamelift.rt.proto.JoinGroup)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 group = 1;</code>
     * @return The group.
     */
    int getGroup();
  }
  /**
   * Protobuf type {@code com.gamelift.rt.proto.JoinGroup}
   */
  public static final class JoinGroup extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.gamelift.rt.proto.JoinGroup)
      JoinGroupOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JoinGroup.newBuilder() to construct.
    private JoinGroup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JoinGroup() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new JoinGroup();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JoinGroup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              group_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gamelift.rt.proto.GroupMessages.internal_static_com_gamelift_rt_proto_JoinGroup_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gamelift.rt.proto.GroupMessages.internal_static_com_gamelift_rt_proto_JoinGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gamelift.rt.proto.GroupMessages.JoinGroup.class, com.gamelift.rt.proto.GroupMessages.JoinGroup.Builder.class);
    }

    public static final int GROUP_FIELD_NUMBER = 1;
    private int group_;
    /**
     * <code>int32 group = 1;</code>
     * @return The group.
     */
    @java.lang.Override
    public int getGroup() {
      return group_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (group_ != 0) {
        output.writeInt32(1, group_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (group_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, group_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gamelift.rt.proto.GroupMessages.JoinGroup)) {
        return super.equals(obj);
      }
      com.gamelift.rt.proto.GroupMessages.JoinGroup other = (com.gamelift.rt.proto.GroupMessages.JoinGroup) obj;

      if (getGroup()
          != other.getGroup()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroup();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gamelift.rt.proto.GroupMessages.JoinGroup parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gamelift.rt.proto.GroupMessages.JoinGroup parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gamelift.rt.proto.GroupMessages.JoinGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gamelift.rt.proto.GroupMessages.JoinGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gamelift.rt.proto.GroupMessages.JoinGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gamelift.rt.proto.GroupMessages.JoinGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gamelift.rt.proto.GroupMessages.JoinGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gamelift.rt.proto.GroupMessages.JoinGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gamelift.rt.proto.GroupMessages.JoinGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gamelift.rt.proto.GroupMessages.JoinGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gamelift.rt.proto.GroupMessages.JoinGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gamelift.rt.proto.GroupMessages.JoinGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gamelift.rt.proto.GroupMessages.JoinGroup prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gamelift.rt.proto.JoinGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.gamelift.rt.proto.JoinGroup)
        com.gamelift.rt.proto.GroupMessages.JoinGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gamelift.rt.proto.GroupMessages.internal_static_com_gamelift_rt_proto_JoinGroup_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gamelift.rt.proto.GroupMessages.internal_static_com_gamelift_rt_proto_JoinGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gamelift.rt.proto.GroupMessages.JoinGroup.class, com.gamelift.rt.proto.GroupMessages.JoinGroup.Builder.class);
      }

      // Construct using com.gamelift.rt.proto.GroupMessages.JoinGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        group_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gamelift.rt.proto.GroupMessages.internal_static_com_gamelift_rt_proto_JoinGroup_descriptor;
      }

      @java.lang.Override
      public com.gamelift.rt.proto.GroupMessages.JoinGroup getDefaultInstanceForType() {
        return com.gamelift.rt.proto.GroupMessages.JoinGroup.getDefaultInstance();
      }

      @java.lang.Override
      public com.gamelift.rt.proto.GroupMessages.JoinGroup build() {
        com.gamelift.rt.proto.GroupMessages.JoinGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gamelift.rt.proto.GroupMessages.JoinGroup buildPartial() {
        com.gamelift.rt.proto.GroupMessages.JoinGroup result = new com.gamelift.rt.proto.GroupMessages.JoinGroup(this);
        result.group_ = group_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gamelift.rt.proto.GroupMessages.JoinGroup) {
          return mergeFrom((com.gamelift.rt.proto.GroupMessages.JoinGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gamelift.rt.proto.GroupMessages.JoinGroup other) {
        if (other == com.gamelift.rt.proto.GroupMessages.JoinGroup.getDefaultInstance()) return this;
        if (other.getGroup() != 0) {
          setGroup(other.getGroup());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gamelift.rt.proto.GroupMessages.JoinGroup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gamelift.rt.proto.GroupMessages.JoinGroup) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int group_ ;
      /**
       * <code>int32 group = 1;</code>
       * @return The group.
       */
      @java.lang.Override
      public int getGroup() {
        return group_;
      }
      /**
       * <code>int32 group = 1;</code>
       * @param value The group to set.
       * @return This builder for chaining.
       */
      public Builder setGroup(int value) {
        
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 group = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroup() {
        
        group_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.gamelift.rt.proto.JoinGroup)
    }

    // @@protoc_insertion_point(class_scope:com.gamelift.rt.proto.JoinGroup)
    private static final com.gamelift.rt.proto.GroupMessages.JoinGroup DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gamelift.rt.proto.GroupMessages.JoinGroup();
    }

    public static com.gamelift.rt.proto.GroupMessages.JoinGroup getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JoinGroup>
        PARSER = new com.google.protobuf.AbstractParser<JoinGroup>() {
      @java.lang.Override
      public JoinGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JoinGroup(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JoinGroup> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JoinGroup> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gamelift.rt.proto.GroupMessages.JoinGroup getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LeaveGroupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.gamelift.rt.proto.LeaveGroup)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 group = 1;</code>
     * @return The group.
     */
    int getGroup();
  }
  /**
   * Protobuf type {@code com.gamelift.rt.proto.LeaveGroup}
   */
  public static final class LeaveGroup extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.gamelift.rt.proto.LeaveGroup)
      LeaveGroupOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LeaveGroup.newBuilder() to construct.
    private LeaveGroup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LeaveGroup() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LeaveGroup();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LeaveGroup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              group_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gamelift.rt.proto.GroupMessages.internal_static_com_gamelift_rt_proto_LeaveGroup_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gamelift.rt.proto.GroupMessages.internal_static_com_gamelift_rt_proto_LeaveGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gamelift.rt.proto.GroupMessages.LeaveGroup.class, com.gamelift.rt.proto.GroupMessages.LeaveGroup.Builder.class);
    }

    public static final int GROUP_FIELD_NUMBER = 1;
    private int group_;
    /**
     * <code>int32 group = 1;</code>
     * @return The group.
     */
    @java.lang.Override
    public int getGroup() {
      return group_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (group_ != 0) {
        output.writeInt32(1, group_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (group_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, group_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gamelift.rt.proto.GroupMessages.LeaveGroup)) {
        return super.equals(obj);
      }
      com.gamelift.rt.proto.GroupMessages.LeaveGroup other = (com.gamelift.rt.proto.GroupMessages.LeaveGroup) obj;

      if (getGroup()
          != other.getGroup()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroup();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gamelift.rt.proto.GroupMessages.LeaveGroup parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gamelift.rt.proto.GroupMessages.LeaveGroup parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gamelift.rt.proto.GroupMessages.LeaveGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gamelift.rt.proto.GroupMessages.LeaveGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gamelift.rt.proto.GroupMessages.LeaveGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gamelift.rt.proto.GroupMessages.LeaveGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gamelift.rt.proto.GroupMessages.LeaveGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gamelift.rt.proto.GroupMessages.LeaveGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gamelift.rt.proto.GroupMessages.LeaveGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gamelift.rt.proto.GroupMessages.LeaveGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gamelift.rt.proto.GroupMessages.LeaveGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gamelift.rt.proto.GroupMessages.LeaveGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gamelift.rt.proto.GroupMessages.LeaveGroup prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gamelift.rt.proto.LeaveGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.gamelift.rt.proto.LeaveGroup)
        com.gamelift.rt.proto.GroupMessages.LeaveGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gamelift.rt.proto.GroupMessages.internal_static_com_gamelift_rt_proto_LeaveGroup_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gamelift.rt.proto.GroupMessages.internal_static_com_gamelift_rt_proto_LeaveGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gamelift.rt.proto.GroupMessages.LeaveGroup.class, com.gamelift.rt.proto.GroupMessages.LeaveGroup.Builder.class);
      }

      // Construct using com.gamelift.rt.proto.GroupMessages.LeaveGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        group_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gamelift.rt.proto.GroupMessages.internal_static_com_gamelift_rt_proto_LeaveGroup_descriptor;
      }

      @java.lang.Override
      public com.gamelift.rt.proto.GroupMessages.LeaveGroup getDefaultInstanceForType() {
        return com.gamelift.rt.proto.GroupMessages.LeaveGroup.getDefaultInstance();
      }

      @java.lang.Override
      public com.gamelift.rt.proto.GroupMessages.LeaveGroup build() {
        com.gamelift.rt.proto.GroupMessages.LeaveGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gamelift.rt.proto.GroupMessages.LeaveGroup buildPartial() {
        com.gamelift.rt.proto.GroupMessages.LeaveGroup result = new com.gamelift.rt.proto.GroupMessages.LeaveGroup(this);
        result.group_ = group_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gamelift.rt.proto.GroupMessages.LeaveGroup) {
          return mergeFrom((com.gamelift.rt.proto.GroupMessages.LeaveGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gamelift.rt.proto.GroupMessages.LeaveGroup other) {
        if (other == com.gamelift.rt.proto.GroupMessages.LeaveGroup.getDefaultInstance()) return this;
        if (other.getGroup() != 0) {
          setGroup(other.getGroup());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gamelift.rt.proto.GroupMessages.LeaveGroup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gamelift.rt.proto.GroupMessages.LeaveGroup) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int group_ ;
      /**
       * <code>int32 group = 1;</code>
       * @return The group.
       */
      @java.lang.Override
      public int getGroup() {
        return group_;
      }
      /**
       * <code>int32 group = 1;</code>
       * @param value The group to set.
       * @return This builder for chaining.
       */
      public Builder setGroup(int value) {
        
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 group = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroup() {
        
        group_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.gamelift.rt.proto.LeaveGroup)
    }

    // @@protoc_insertion_point(class_scope:com.gamelift.rt.proto.LeaveGroup)
    private static final com.gamelift.rt.proto.GroupMessages.LeaveGroup DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gamelift.rt.proto.GroupMessages.LeaveGroup();
    }

    public static com.gamelift.rt.proto.GroupMessages.LeaveGroup getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LeaveGroup>
        PARSER = new com.google.protobuf.AbstractParser<LeaveGroup>() {
      @java.lang.Override
      public LeaveGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LeaveGroup(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LeaveGroup> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LeaveGroup> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gamelift.rt.proto.GroupMessages.LeaveGroup getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RequestGroupMembershipOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.gamelift.rt.proto.RequestGroupMembership)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 group = 1;</code>
     * @return The group.
     */
    int getGroup();
  }
  /**
   * Protobuf type {@code com.gamelift.rt.proto.RequestGroupMembership}
   */
  public static final class RequestGroupMembership extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.gamelift.rt.proto.RequestGroupMembership)
      RequestGroupMembershipOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestGroupMembership.newBuilder() to construct.
    private RequestGroupMembership(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestGroupMembership() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RequestGroupMembership();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestGroupMembership(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              group_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gamelift.rt.proto.GroupMessages.internal_static_com_gamelift_rt_proto_RequestGroupMembership_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gamelift.rt.proto.GroupMessages.internal_static_com_gamelift_rt_proto_RequestGroupMembership_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gamelift.rt.proto.GroupMessages.RequestGroupMembership.class, com.gamelift.rt.proto.GroupMessages.RequestGroupMembership.Builder.class);
    }

    public static final int GROUP_FIELD_NUMBER = 1;
    private int group_;
    /**
     * <code>int32 group = 1;</code>
     * @return The group.
     */
    @java.lang.Override
    public int getGroup() {
      return group_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (group_ != 0) {
        output.writeInt32(1, group_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (group_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, group_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gamelift.rt.proto.GroupMessages.RequestGroupMembership)) {
        return super.equals(obj);
      }
      com.gamelift.rt.proto.GroupMessages.RequestGroupMembership other = (com.gamelift.rt.proto.GroupMessages.RequestGroupMembership) obj;

      if (getGroup()
          != other.getGroup()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroup();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gamelift.rt.proto.GroupMessages.RequestGroupMembership parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gamelift.rt.proto.GroupMessages.RequestGroupMembership parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gamelift.rt.proto.GroupMessages.RequestGroupMembership parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gamelift.rt.proto.GroupMessages.RequestGroupMembership parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gamelift.rt.proto.GroupMessages.RequestGroupMembership parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gamelift.rt.proto.GroupMessages.RequestGroupMembership parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gamelift.rt.proto.GroupMessages.RequestGroupMembership parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gamelift.rt.proto.GroupMessages.RequestGroupMembership parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gamelift.rt.proto.GroupMessages.RequestGroupMembership parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gamelift.rt.proto.GroupMessages.RequestGroupMembership parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gamelift.rt.proto.GroupMessages.RequestGroupMembership parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gamelift.rt.proto.GroupMessages.RequestGroupMembership parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gamelift.rt.proto.GroupMessages.RequestGroupMembership prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gamelift.rt.proto.RequestGroupMembership}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.gamelift.rt.proto.RequestGroupMembership)
        com.gamelift.rt.proto.GroupMessages.RequestGroupMembershipOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gamelift.rt.proto.GroupMessages.internal_static_com_gamelift_rt_proto_RequestGroupMembership_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gamelift.rt.proto.GroupMessages.internal_static_com_gamelift_rt_proto_RequestGroupMembership_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gamelift.rt.proto.GroupMessages.RequestGroupMembership.class, com.gamelift.rt.proto.GroupMessages.RequestGroupMembership.Builder.class);
      }

      // Construct using com.gamelift.rt.proto.GroupMessages.RequestGroupMembership.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        group_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gamelift.rt.proto.GroupMessages.internal_static_com_gamelift_rt_proto_RequestGroupMembership_descriptor;
      }

      @java.lang.Override
      public com.gamelift.rt.proto.GroupMessages.RequestGroupMembership getDefaultInstanceForType() {
        return com.gamelift.rt.proto.GroupMessages.RequestGroupMembership.getDefaultInstance();
      }

      @java.lang.Override
      public com.gamelift.rt.proto.GroupMessages.RequestGroupMembership build() {
        com.gamelift.rt.proto.GroupMessages.RequestGroupMembership result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gamelift.rt.proto.GroupMessages.RequestGroupMembership buildPartial() {
        com.gamelift.rt.proto.GroupMessages.RequestGroupMembership result = new com.gamelift.rt.proto.GroupMessages.RequestGroupMembership(this);
        result.group_ = group_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gamelift.rt.proto.GroupMessages.RequestGroupMembership) {
          return mergeFrom((com.gamelift.rt.proto.GroupMessages.RequestGroupMembership)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gamelift.rt.proto.GroupMessages.RequestGroupMembership other) {
        if (other == com.gamelift.rt.proto.GroupMessages.RequestGroupMembership.getDefaultInstance()) return this;
        if (other.getGroup() != 0) {
          setGroup(other.getGroup());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gamelift.rt.proto.GroupMessages.RequestGroupMembership parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gamelift.rt.proto.GroupMessages.RequestGroupMembership) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int group_ ;
      /**
       * <code>int32 group = 1;</code>
       * @return The group.
       */
      @java.lang.Override
      public int getGroup() {
        return group_;
      }
      /**
       * <code>int32 group = 1;</code>
       * @param value The group to set.
       * @return This builder for chaining.
       */
      public Builder setGroup(int value) {
        
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 group = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroup() {
        
        group_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.gamelift.rt.proto.RequestGroupMembership)
    }

    // @@protoc_insertion_point(class_scope:com.gamelift.rt.proto.RequestGroupMembership)
    private static final com.gamelift.rt.proto.GroupMessages.RequestGroupMembership DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gamelift.rt.proto.GroupMessages.RequestGroupMembership();
    }

    public static com.gamelift.rt.proto.GroupMessages.RequestGroupMembership getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestGroupMembership>
        PARSER = new com.google.protobuf.AbstractParser<RequestGroupMembership>() {
      @java.lang.Override
      public RequestGroupMembership parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestGroupMembership(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestGroupMembership> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestGroupMembership> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gamelift.rt.proto.GroupMessages.RequestGroupMembership getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GroupMembershipUpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.gamelift.rt.proto.GroupMembershipUpdate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 group = 1;</code>
     * @return The group.
     */
    int getGroup();

    /**
     * <code>repeated int32 players = 2;</code>
     * @return A list containing the players.
     */
    java.util.List<java.lang.Integer> getPlayersList();
    /**
     * <code>repeated int32 players = 2;</code>
     * @return The count of players.
     */
    int getPlayersCount();
    /**
     * <code>repeated int32 players = 2;</code>
     * @param index The index of the element to return.
     * @return The players at the given index.
     */
    int getPlayers(int index);
  }
  /**
   * Protobuf type {@code com.gamelift.rt.proto.GroupMembershipUpdate}
   */
  public static final class GroupMembershipUpdate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.gamelift.rt.proto.GroupMembershipUpdate)
      GroupMembershipUpdateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GroupMembershipUpdate.newBuilder() to construct.
    private GroupMembershipUpdate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GroupMembershipUpdate() {
      players_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GroupMembershipUpdate();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GroupMembershipUpdate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              group_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                players_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              players_.addInt(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                players_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                players_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          players_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gamelift.rt.proto.GroupMessages.internal_static_com_gamelift_rt_proto_GroupMembershipUpdate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gamelift.rt.proto.GroupMessages.internal_static_com_gamelift_rt_proto_GroupMembershipUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate.class, com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate.Builder.class);
    }

    public static final int GROUP_FIELD_NUMBER = 1;
    private int group_;
    /**
     * <code>int32 group = 1;</code>
     * @return The group.
     */
    @java.lang.Override
    public int getGroup() {
      return group_;
    }

    public static final int PLAYERS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList players_;
    /**
     * <code>repeated int32 players = 2;</code>
     * @return A list containing the players.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getPlayersList() {
      return players_;
    }
    /**
     * <code>repeated int32 players = 2;</code>
     * @return The count of players.
     */
    public int getPlayersCount() {
      return players_.size();
    }
    /**
     * <code>repeated int32 players = 2;</code>
     * @param index The index of the element to return.
     * @return The players at the given index.
     */
    public int getPlayers(int index) {
      return players_.getInt(index);
    }
    private int playersMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (group_ != 0) {
        output.writeInt32(1, group_);
      }
      if (getPlayersList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(playersMemoizedSerializedSize);
      }
      for (int i = 0; i < players_.size(); i++) {
        output.writeInt32NoTag(players_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (group_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, group_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < players_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(players_.getInt(i));
        }
        size += dataSize;
        if (!getPlayersList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        playersMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate)) {
        return super.equals(obj);
      }
      com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate other = (com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate) obj;

      if (getGroup()
          != other.getGroup()) return false;
      if (!getPlayersList()
          .equals(other.getPlayersList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroup();
      if (getPlayersCount() > 0) {
        hash = (37 * hash) + PLAYERS_FIELD_NUMBER;
        hash = (53 * hash) + getPlayersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.gamelift.rt.proto.GroupMembershipUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.gamelift.rt.proto.GroupMembershipUpdate)
        com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gamelift.rt.proto.GroupMessages.internal_static_com_gamelift_rt_proto_GroupMembershipUpdate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gamelift.rt.proto.GroupMessages.internal_static_com_gamelift_rt_proto_GroupMembershipUpdate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate.class, com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate.Builder.class);
      }

      // Construct using com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        group_ = 0;

        players_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gamelift.rt.proto.GroupMessages.internal_static_com_gamelift_rt_proto_GroupMembershipUpdate_descriptor;
      }

      @java.lang.Override
      public com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate getDefaultInstanceForType() {
        return com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate.getDefaultInstance();
      }

      @java.lang.Override
      public com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate build() {
        com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate buildPartial() {
        com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate result = new com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate(this);
        int from_bitField0_ = bitField0_;
        result.group_ = group_;
        if (((bitField0_ & 0x00000001) != 0)) {
          players_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.players_ = players_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate) {
          return mergeFrom((com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate other) {
        if (other == com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate.getDefaultInstance()) return this;
        if (other.getGroup() != 0) {
          setGroup(other.getGroup());
        }
        if (!other.players_.isEmpty()) {
          if (players_.isEmpty()) {
            players_ = other.players_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePlayersIsMutable();
            players_.addAll(other.players_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int group_ ;
      /**
       * <code>int32 group = 1;</code>
       * @return The group.
       */
      @java.lang.Override
      public int getGroup() {
        return group_;
      }
      /**
       * <code>int32 group = 1;</code>
       * @param value The group to set.
       * @return This builder for chaining.
       */
      public Builder setGroup(int value) {
        
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 group = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroup() {
        
        group_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList players_ = emptyIntList();
      private void ensurePlayersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          players_ = mutableCopy(players_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 players = 2;</code>
       * @return A list containing the players.
       */
      public java.util.List<java.lang.Integer>
          getPlayersList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(players_) : players_;
      }
      /**
       * <code>repeated int32 players = 2;</code>
       * @return The count of players.
       */
      public int getPlayersCount() {
        return players_.size();
      }
      /**
       * <code>repeated int32 players = 2;</code>
       * @param index The index of the element to return.
       * @return The players at the given index.
       */
      public int getPlayers(int index) {
        return players_.getInt(index);
      }
      /**
       * <code>repeated int32 players = 2;</code>
       * @param index The index to set the value at.
       * @param value The players to set.
       * @return This builder for chaining.
       */
      public Builder setPlayers(
          int index, int value) {
        ensurePlayersIsMutable();
        players_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 players = 2;</code>
       * @param value The players to add.
       * @return This builder for chaining.
       */
      public Builder addPlayers(int value) {
        ensurePlayersIsMutable();
        players_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 players = 2;</code>
       * @param values The players to add.
       * @return This builder for chaining.
       */
      public Builder addAllPlayers(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensurePlayersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, players_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 players = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayers() {
        players_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.gamelift.rt.proto.GroupMembershipUpdate)
    }

    // @@protoc_insertion_point(class_scope:com.gamelift.rt.proto.GroupMembershipUpdate)
    private static final com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate();
    }

    public static com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GroupMembershipUpdate>
        PARSER = new com.google.protobuf.AbstractParser<GroupMembershipUpdate>() {
      @java.lang.Override
      public GroupMembershipUpdate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GroupMembershipUpdate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GroupMembershipUpdate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GroupMembershipUpdate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.gamelift.rt.proto.GroupMessages.GroupMembershipUpdate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gamelift_rt_proto_JoinGroup_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gamelift_rt_proto_JoinGroup_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gamelift_rt_proto_LeaveGroup_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gamelift_rt_proto_LeaveGroup_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gamelift_rt_proto_RequestGroupMembership_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gamelift_rt_proto_RequestGroupMembership_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gamelift_rt_proto_GroupMembershipUpdate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gamelift_rt_proto_GroupMembershipUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031proto/GroupMessages.proto\022\025com.gamelif" +
      "t.rt.proto\"\032\n\tJoinGroup\022\r\n\005group\030\001 \001(\005\"\033" +
      "\n\nLeaveGroup\022\r\n\005group\030\001 \001(\005\"\'\n\026RequestGr" +
      "oupMembership\022\r\n\005group\030\001 \001(\005\"7\n\025GroupMem" +
      "bershipUpdate\022\r\n\005group\030\001 \001(\005\022\017\n\007players\030" +
      "\002 \003(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_gamelift_rt_proto_JoinGroup_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gamelift_rt_proto_JoinGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gamelift_rt_proto_JoinGroup_descriptor,
        new java.lang.String[] { "Group", });
    internal_static_com_gamelift_rt_proto_LeaveGroup_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_gamelift_rt_proto_LeaveGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gamelift_rt_proto_LeaveGroup_descriptor,
        new java.lang.String[] { "Group", });
    internal_static_com_gamelift_rt_proto_RequestGroupMembership_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_gamelift_rt_proto_RequestGroupMembership_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gamelift_rt_proto_RequestGroupMembership_descriptor,
        new java.lang.String[] { "Group", });
    internal_static_com_gamelift_rt_proto_GroupMembershipUpdate_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_gamelift_rt_proto_GroupMembershipUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gamelift_rt_proto_GroupMembershipUpdate_descriptor,
        new java.lang.String[] { "Group", "Players", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
