//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/CoreCommands.proto

package com.gamelift.rt.proto;

@kotlin.jvm.JvmSynthetic
public inline fun loginCommand(block: com.gamelift.rt.proto.LoginCommandKt.Dsl.() -> kotlin.Unit): com.gamelift.rt.proto.CoreCommands.LoginCommand =
  com.gamelift.rt.proto.LoginCommandKt.Dsl._create(com.gamelift.rt.proto.CoreCommands.LoginCommand.newBuilder()).apply { block() }._build()
public object LoginCommandKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.gamelift.rt.proto.CoreCommands.LoginCommand.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.gamelift.rt.proto.CoreCommands.LoginCommand.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.gamelift.rt.proto.CoreCommands.LoginCommand = _builder.build()

    /**
     * <code>string playerSessionId = 1;</code>
     */
    public var playerSessionId: kotlin.String
      @JvmName("getPlayerSessionId")
      get() = _builder.getPlayerSessionId()
      @JvmName("setPlayerSessionId")
      set(value) {
        _builder.setPlayerSessionId(value)
      }
    /**
     * <code>string playerSessionId = 1;</code>
     */
    public fun clearPlayerSessionId() {
      _builder.clearPlayerSessionId()
    }

    /**
     * <code>int32 clientVersion = 2;</code>
     */
    public var clientVersion: kotlin.Int
      @JvmName("getClientVersion")
      get() = _builder.getClientVersion()
      @JvmName("setClientVersion")
      set(value) {
        _builder.setClientVersion(value)
      }
    /**
     * <code>int32 clientVersion = 2;</code>
     */
    public fun clearClientVersion() {
      _builder.clearClientVersion()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.gamelift.rt.proto.CoreCommands.LoginCommand.copy(block: com.gamelift.rt.proto.LoginCommandKt.Dsl.() -> kotlin.Unit): com.gamelift.rt.proto.CoreCommands.LoginCommand =
  com.gamelift.rt.proto.LoginCommandKt.Dsl._create(this.toBuilder()).apply { block() }._build()
