//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/CoreCommands.proto

package com.gamelift.rt.proto;

@kotlin.jvm.JvmSynthetic
public inline fun playerConnectMessage(block: com.gamelift.rt.proto.PlayerConnectMessageKt.Dsl.() -> kotlin.Unit): com.gamelift.rt.proto.CoreCommands.PlayerConnectMessage =
  com.gamelift.rt.proto.PlayerConnectMessageKt.Dsl._create(com.gamelift.rt.proto.CoreCommands.PlayerConnectMessage.newBuilder()).apply { block() }._build()
public object PlayerConnectMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.gamelift.rt.proto.CoreCommands.PlayerConnectMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.gamelift.rt.proto.CoreCommands.PlayerConnectMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.gamelift.rt.proto.CoreCommands.PlayerConnectMessage = _builder.build()

    /**
     * <code>int32 peerId = 1;</code>
     */
    public var peerId: kotlin.Int
      @JvmName("getPeerId")
      get() = _builder.getPeerId()
      @JvmName("setPeerId")
      set(value) {
        _builder.setPeerId(value)
      }
    /**
     * <code>int32 peerId = 1;</code>
     */
    public fun clearPeerId() {
      _builder.clearPeerId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.gamelift.rt.proto.CoreCommands.PlayerConnectMessage.copy(block: com.gamelift.rt.proto.PlayerConnectMessageKt.Dsl.() -> kotlin.Unit): com.gamelift.rt.proto.CoreCommands.PlayerConnectMessage =
  com.gamelift.rt.proto.PlayerConnectMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()
