//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/GroupMessages.proto

package com.gamelift.rt.proto;

@kotlin.jvm.JvmSynthetic
public inline fun requestGroupMembership(block: com.gamelift.rt.proto.RequestGroupMembershipKt.Dsl.() -> kotlin.Unit): com.gamelift.rt.proto.GroupMessages.RequestGroupMembership =
  com.gamelift.rt.proto.RequestGroupMembershipKt.Dsl._create(com.gamelift.rt.proto.GroupMessages.RequestGroupMembership.newBuilder()).apply { block() }._build()
public object RequestGroupMembershipKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.gamelift.rt.proto.GroupMessages.RequestGroupMembership.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.gamelift.rt.proto.GroupMessages.RequestGroupMembership.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.gamelift.rt.proto.GroupMessages.RequestGroupMembership = _builder.build()

    /**
     * <code>int32 group = 1;</code>
     */
    public var group: kotlin.Int
      @JvmName("getGroup")
      get() = _builder.getGroup()
      @JvmName("setGroup")
      set(value) {
        _builder.setGroup(value)
      }
    /**
     * <code>int32 group = 1;</code>
     */
    public fun clearGroup() {
      _builder.clearGroup()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.gamelift.rt.proto.GroupMessages.RequestGroupMembership.copy(block: com.gamelift.rt.proto.RequestGroupMembershipKt.Dsl.() -> kotlin.Unit): com.gamelift.rt.proto.GroupMessages.RequestGroupMembership =
  com.gamelift.rt.proto.RequestGroupMembershipKt.Dsl._create(this.toBuilder()).apply { block() }._build()
