//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/CoreCommands.proto

package com.gamelift.rt.proto;

@kotlin.jvm.JvmSynthetic
public inline fun uDPConnectMessage(block: com.gamelift.rt.proto.UDPConnectMessageKt.Dsl.() -> kotlin.Unit): com.gamelift.rt.proto.CoreCommands.UDPConnectMessage =
  com.gamelift.rt.proto.UDPConnectMessageKt.Dsl._create(com.gamelift.rt.proto.CoreCommands.UDPConnectMessage.newBuilder()).apply { block() }._build()
public object UDPConnectMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.gamelift.rt.proto.CoreCommands.UDPConnectMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.gamelift.rt.proto.CoreCommands.UDPConnectMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.gamelift.rt.proto.CoreCommands.UDPConnectMessage = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.gamelift.rt.proto.CoreCommands.UDPConnectMessage.copy(block: com.gamelift.rt.proto.UDPConnectMessageKt.Dsl.() -> kotlin.Unit): com.gamelift.rt.proto.CoreCommands.UDPConnectMessage =
  com.gamelift.rt.proto.UDPConnectMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()
