//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/CoreCommands.proto

package com.gamelift.rt.proto;

@kotlin.jvm.JvmSynthetic
public inline fun verifyIdentityResult(block: com.gamelift.rt.proto.VerifyIdentityResultKt.Dsl.() -> kotlin.Unit): com.gamelift.rt.proto.CoreCommands.VerifyIdentityResult =
  com.gamelift.rt.proto.VerifyIdentityResultKt.Dsl._create(com.gamelift.rt.proto.CoreCommands.VerifyIdentityResult.newBuilder()).apply { block() }._build()
public object VerifyIdentityResultKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.gamelift.rt.proto.CoreCommands.VerifyIdentityResult.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.gamelift.rt.proto.CoreCommands.VerifyIdentityResult.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.gamelift.rt.proto.CoreCommands.VerifyIdentityResult = _builder.build()

    /**
     * <code>bool success = 1;</code>
     */
    public var success: kotlin.Boolean
      @JvmName("getSuccess")
      get() = _builder.getSuccess()
      @JvmName("setSuccess")
      set(value) {
        _builder.setSuccess(value)
      }
    /**
     * <code>bool success = 1;</code>
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }

    /**
     * <code>int32 peerId = 2;</code>
     */
    public var peerId: kotlin.Int
      @JvmName("getPeerId")
      get() = _builder.getPeerId()
      @JvmName("setPeerId")
      set(value) {
        _builder.setPeerId(value)
      }
    /**
     * <code>int32 peerId = 2;</code>
     */
    public fun clearPeerId() {
      _builder.clearPeerId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.gamelift.rt.proto.CoreCommands.VerifyIdentityResult.copy(block: com.gamelift.rt.proto.VerifyIdentityResultKt.Dsl.() -> kotlin.Unit): com.gamelift.rt.proto.CoreCommands.VerifyIdentityResult =
  com.gamelift.rt.proto.VerifyIdentityResultKt.Dsl._create(this.toBuilder()).apply { block() }._build()
