//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/CoreCommands.proto

package com.gamelift.rt.proto;

@kotlin.jvm.JvmSynthetic
public inline fun verifyIdentityCommand(block: com.gamelift.rt.proto.VerifyIdentityCommandKt.Dsl.() -> kotlin.Unit): com.gamelift.rt.proto.CoreCommands.VerifyIdentityCommand =
  com.gamelift.rt.proto.VerifyIdentityCommandKt.Dsl._create(com.gamelift.rt.proto.CoreCommands.VerifyIdentityCommand.newBuilder()).apply { block() }._build()
public object VerifyIdentityCommandKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.gamelift.rt.proto.CoreCommands.VerifyIdentityCommand.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.gamelift.rt.proto.CoreCommands.VerifyIdentityCommand.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.gamelift.rt.proto.CoreCommands.VerifyIdentityCommand = _builder.build()

    /**
     * <code>int32 peerId = 1;</code>
     */
    public var peerId: kotlin.Int
      @JvmName("getPeerId")
      get() = _builder.getPeerId()
      @JvmName("setPeerId")
      set(value) {
        _builder.setPeerId(value)
      }
    /**
     * <code>int32 peerId = 1;</code>
     */
    public fun clearPeerId() {
      _builder.clearPeerId()
    }

    /**
     * <code>string connectToken = 2;</code>
     */
    public var connectToken: kotlin.String
      @JvmName("getConnectToken")
      get() = _builder.getConnectToken()
      @JvmName("setConnectToken")
      set(value) {
        _builder.setConnectToken(value)
      }
    /**
     * <code>string connectToken = 2;</code>
     */
    public fun clearConnectToken() {
      _builder.clearConnectToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.gamelift.rt.proto.CoreCommands.VerifyIdentityCommand.copy(block: com.gamelift.rt.proto.VerifyIdentityCommandKt.Dsl.() -> kotlin.Unit): com.gamelift.rt.proto.CoreCommands.VerifyIdentityCommand =
  com.gamelift.rt.proto.VerifyIdentityCommandKt.Dsl._create(this.toBuilder()).apply { block() }._build()
